#!/bin/python

import sys
import json
import asyncio

import src.lib as lib
import src.tui as tui

class maindl():
    def __init__(self):
        self.arguments = sys.argv

    async def run(self):
        options = self.arguments[1]

        if options == "pull":
            driver = lib.find_os()
            driver.get("https://instagram.com")
            tui.prompt_login()
            sec = tui.prompt_scroll()
            aagt_items = lib.cache_links(driver, sec)

            lib.save_links(aagt_items)

            await lib.bundle_downloads(aagt_items)

        elif options == "download":
            filename = self.arguments[2]
            path = f"saved-lists/{filename}"

            try:
                f = open(path)
                links = json.load(f)
                await lib.bundle_downloads(links)
            except:
                print("type in the EXACT filename including spaces, fullstops and the .json at the end: \n"
                      "For example, if your file was in the directory /saved-lists/2022-08-14 13.21.30.092375.json, \n"
                      "you would type '2022-08-14 13.21.30.092375.json'")

        elif options == "help":
            print("""Instadl Help Menu:
            instadl pull                    - pulls images from instagram, saves links in saved-lists and downloads to output
            instadl download LISTNAME       - downloads images from a saved list""")

        else:
            print("Invalid input - try running 'python instadl help' instead")
            return


if __name__ == '__main__':
    maindl = maindl()
    asyncio.run(maindl.run())